version: '3.9'

services:
  backend:
    build: 
      context: ./ex-back/
    command: /bin/sh -c "cd /app && node index.js"
    volumes:
      - ./ex-back:/app
    networks:
      back:

  frontend:
    build: 
      context: ./ex-front/
    volumes:
      - front-build:/app/build
    networks:
      back:

  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports: 
      - 8080:8080
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - front-build:/static
    depends_on:
      - backend
      - frontend
    networks:
      back:
    

networks:
  back:
    ipam:
      config:
        - subnet: 172.194.32.0/24

volumes:
  front-build:
    driver: local